name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: SumUpTo_Public.PositiveNumbers
      id: sumupto_public-positivenumbers
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: SumUpTo_Public.PositiveNumbers
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 5
    - name: SumUpTo_Public.EdgeCases
      id: sumupto_public-edgecases
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: SumUpTo_Public.EdgeCases
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SUMUPTO_PUBLIC-POSITIVENUMBERS_RESULTS: "${{steps.sumupto_public-positivenumbers.outputs.result}}"
        SUMUPTO_PUBLIC-EDGECASES_RESULTS: "${{steps.sumupto_public-edgecases.outputs.result}}"
      with:
        runners: sumupto_public-positivenumbers,sumupto_public-edgecases
