name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Positive Numbers Test ---
      - name: Run Positive Numbers Test
        id: SumUptoTest-PositiveNumbers
        uses: classroom-resources/autograding-command-grader@v1
        with:
          command: "./bin/sum_up_test_positive.sh"
          timeout: 10

      # --- Edge Cases Test ---
      - name: Run Edge Cases Test
        id: SumUptoTest-EdgeCases
        uses: classroom-resources/autograding-command-grader@v1
        with:
          command: "./bin/sum_up_test_edgecases.sh"
          timeout: 10

      # --- Reporter Step ---
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: |
            sumuptotest-positivenumbers
            sumuptotest-edgecases
        env:
          SUMUPTEST_POSITIVENUMBERS_RESULTS: ${{ steps.sumuptotest-positivenumbers.outputs.result }}
          SUMUPTEST_EDGECASES_RESULTS: ${{ steps.sumuptotest-edgecases.outputs.result }}
